name: 'Deployment Action'
on:
  push:
    branches:
      - main

permissions:
    id-token: write
    contents: read

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    steps:
      - name: 'Configure AWS Credentials'
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::851725365087:role/myles-oidc
          role-session-name: GitHubActions
            
      - name: 'Checkout'
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@97f030cf6dc0b4f5e0da352c7bca9cca34579800 # v3.1.0

      - name: 'Terraform Init'
        id: init
        run: terraform init

      - name: 'Terraform Apply'
        id: apply
        run: terraform apply --auto-approve -no-color